import 'package:flutter/material.dart';
import 'package:nomadair_core/core.dart';
final class RebuildTrackerWidget extends StatefulWidget{const RebuildTrackerWidget({super.key});@override State<RebuildTrackerWidget> createState()=>_S();}
final class _S extends State<RebuildTrackerWidget>{bool _anti=false;int _pc=0;@override Widget build(BuildContext ctx){final t=Theme.of(ctx).extension<NomadThemeExtension>()!;return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[SwitchListTile(value:_anti,onChanged:(v)=>setState((){_anti=v;_pc=0;}),title:Text(_anti?'Anti-pattern: state in parent':'Correct: state isolated',style:AppTypography.labelLarge.copyWith(color:_anti?t.errorColor:t.successColor)),secondary:Icon(_anti?Icons.warning_amber:Icons.check_circle,color:_anti?t.errorColor:t.successColor)),const SizedBox(height:AppSpacing.sm),Padding(padding:const EdgeInsets.symmetric(horizontal:AppSpacing.md),child:_anti?_AntiP(c:_pc,onInc:()=>setState(()=>_pc++)):const _Correct())]);}}
final class _Correct extends StatelessWidget{const _Correct();@override Widget build(BuildContext ctx)=>Column(children:[_Box(label:'Sibling A (never rebuilds)',color:AppColors.green500),const SizedBox(height:AppSpacing.sm),const _IsoCounter(),const SizedBox(height:AppSpacing.sm),_Box(label:'Sibling B (never rebuilds)',color:AppColors.green500)]);}
final class _IsoCounter extends StatefulWidget{const _IsoCounter();@override State<_IsoCounter> createState()=>_ICS();}
final class _ICS extends State<_IsoCounter>{int _c=0,_b=0;Color _fl=Colors.transparent;void _inc(){setState((){_c++;_fl=AppColors.red500.withAlpha(100);});Future<void>.delayed(const Duration(milliseconds:300),(){if(mounted)setState(()=>_fl=Colors.transparent);});}@override Widget build(BuildContext ctx){_b++;final t=Theme.of(ctx).extension<NomadThemeExtension>()!;return AnimatedContainer(duration:const Duration(milliseconds:200),color:_fl,child:Card(child:Padding(padding:const EdgeInsets.all(AppSpacing.md),child:Column(children:[Text('Isolated Counter',style:AppTypography.labelLarge.copyWith(color:t.onSurfaceColor)),Text('Builds: $_b',style:AppTypography.monoSmall.copyWith(color:t.brandPrimary)),const SizedBox(height:AppSpacing.sm),Row(mainAxisAlignment:MainAxisAlignment.center,children:[IconButton(icon:Icon(Icons.add_circle,color:t.brandPrimary,size:36),onPressed:_inc),Text('$_c',style:AppTypography.displayLarge.copyWith(color:t.onSurfaceColor))])]))));}}
final class _AntiP extends StatefulWidget{const _AntiP({required this.c,required this.onInc});final int c;final VoidCallback onInc;@override State<_AntiP> createState()=>_APS();}
final class _APS extends State<_AntiP>{int _b=0;@override Widget build(BuildContext ctx){_b++;final t=Theme.of(ctx).extension<NomadThemeExtension>()!;return AnimatedContainer(duration:const Duration(milliseconds:200),color:AppColors.red500.withAlpha(_b%2==0?20:60),child:Column(children:[Padding(padding:const EdgeInsets.all(AppSpacing.xs),child:Text('Parent (builds:$_b)',style:AppTypography.monoSmall.copyWith(color:t.errorColor,fontWeight:FontWeight.w700))),_Box(label:'Sibling A — rebuilds!',color:AppColors.red500),const SizedBox(height:AppSpacing.sm),Card(child:Padding(padding:const EdgeInsets.all(AppSpacing.md),child:Row(mainAxisAlignment:MainAxisAlignment.center,children:[IconButton(icon:Icon(Icons.add_circle,color:t.errorColor,size:36),onPressed:widget.onInc),Text('${widget.c}',style:AppTypography.displayLarge.copyWith(color:t.onSurfaceColor))]))),const SizedBox(height:AppSpacing.sm),_Box(label:'Sibling B — rebuilds!',color:AppColors.red500)]));}}
final class _Box extends StatefulWidget{const _Box({required this.label,required this.color});final String label;final Color color;@override State<_Box> createState()=>_BS();}
final class _BS extends State<_Box>{int _b=0;@override Widget build(BuildContext ctx){_b++;final t=Theme.of(ctx).extension<NomadThemeExtension>()!;return Container(decoration:BoxDecoration(color:widget.color.withAlpha(12),borderRadius:BorderRadius.circular(AppSpacing.radiusSm),border:Border.all(color:widget.color.withAlpha(60))),padding:const EdgeInsets.symmetric(horizontal:AppSpacing.md,vertical:AppSpacing.sm),child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Expanded(child:Text(widget.label,style:AppTypography.bodySmall.copyWith(color:t.onSurfaceColor))),Text('builds:$_b',style:AppTypography.monoSmall.copyWith(color:widget.color,fontWeight:FontWeight.w700))]));}}

