import 'dart:async';

import 'package:app_links/app_links.dart';
import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:nomadair_core/core.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'core/config/mock_config.dart';
import 'core/cache/cache_service.dart';
import 'core/cache/hive_cache_service.dart';
import 'core/deeplink/deep_link_handler.dart';
import 'core/services/hive_storage_service.dart';
import 'core/services/local_storage_service.dart';
import 'core/services/theme_preference_service.dart';
import 'features/search/models/recent_search.dart';
import 'features/search/providers/search_criteria_notifier.dart';
import 'features/search/providers/flight_search_notifier.dart';
import 'router/app_router.dart';

/// Lesson 20 — Hive initialised before runApp.
///
/// Order matters:
///   1. Hive.initFlutter()          — sets up the app-documents path
///   2. Hive.registerAdapter(...)   — must happen before openBox
///   3. HiveStorageService.init()   — opens the Hive boxes
///   4. runApp(...)                 — UI starts
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── Hive setup ──────────────────────────────────────────────────
  await Hive.initFlutter();
  Hive.registerAdapter(RecentSearchAdapter()); // generated by build_runner

  final storage = HiveStorageService();
  await storage.init();

  // L22: Hive cache for flight-search results (shared with MockConfig)
  final flightCache = HiveCacheService();
  await flightCache.init();
  MockConfig.bindFlightCache(flightCache);

  // ── Theme pref ──────────────────────────────────────────────────
  SharedPreferences.setMockInitialValues({});
  final svc   = await SharedPrefsThemeService.create();
  final saved = await svc.load();

  runApp(
    MultiProvider(
      providers: [
        // Storage — screens read/write via LocalStorageService
        Provider<LocalStorageService>.value(value: storage),
        Provider<CacheService>.value(value: flightCache),
        ChangeNotifierProvider(create: (_) => SearchCriteriaNotifier()),
        ChangeNotifierProvider(
          create: (_) =>
              FlightSearchNotifier(MockConfig.cachedFlightRepository)),
      ],
      child: NomadAirApp(svc: svc, initialMode: saved)));
}

final class NomadAirApp extends StatefulWidget {
  const NomadAirApp({super.key, required this.svc, required this.initialMode});
  final ThemePreferenceService svc;
  final ThemeMode initialMode;
  static _NomadAirAppState of(BuildContext ctx) =>
      ctx.findAncestorStateOfType<_NomadAirAppState>()!;
  @override State<NomadAirApp> createState() => _NomadAirAppState();
}

final class _NomadAirAppState extends State<NomadAirApp> {
  late ThemeMode _mode;
  StreamSubscription<Uri>? _appLinkSub;

  @override void initState() {
    super.initState();
    _mode = widget.initialMode;
    WidgetsBinding.instance.addPostFrameCallback((_) => _listenAppLinks());
  }

  Future<void> _listenAppLinks() async {
    final appLinks = AppLinks();
    final initial = await appLinks.getInitialLink();
    if (initial != null) _dispatchDeepLink(initial);
    _appLinkSub = appLinks.uriLinkStream.listen(_dispatchDeepLink);
  }

  void _dispatchDeepLink(Uri uri) {
    final ctx = AppRouter.navigatorKey.currentContext;
    if (ctx == null) return;
    if (uri.scheme != 'nomadair') return;
    DeepLinkHandler().handle(uri, ctx);
  }

  @override void dispose() {
    _appLinkSub?.cancel();
    super.dispose();
  }

  ThemeMode get mode => _mode;
  Future<void> setMode(ThemeMode m) async {
    await widget.svc.save(m);
    if (mounted) setState(() => _mode = m);
  }
  @override Widget build(BuildContext context) => MaterialApp.router(
    title: 'NomadAir',
    debugShowCheckedModeBanner: false,
    theme:     NomadAirTheme.light(),
    darkTheme: NomadAirTheme.dark(),
    themeMode: _mode,
    routerConfig: AppRouter.router);
}
